### ISSUE TITLE
App container won't connect to DB container

### ISSUE THREAD

**Issue by bepstein111** [somsakc/docker-observium#18]
Deployed via copy/paste docker-compose.yaml into the Portainer Stack editor.

Here's the docker-compose:
```
# Docker compose file for Observium
# Maintained by somsakc@hotmail.com

version: '3'

services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=PASSWORD1
      - MYSQL_USER=observium
      - MYSQL_PASSWORD=PASSWORD1
      - MYSQL_DATABASE=observium
      - TZ=America/New_York
    volumes:
      - /etc/observium-mysql/:/var/lib/mysql
    networks:
      - back-tier
    restart: always


  app:
    image: mbixtech/observium
    environment:
      - OBSERVIUM_ADMIN_USER=admin
      - OBSERVIUM_ADMIN_PASS=PASSWORD2
      - OBSERVIUM_DB_HOST=db
      - OBSERVIUM_DB_NAME=observium
      - OBSERVIUM_DB_USER=observium 
      - OBSERVIUM_DB_PASS=PASSWORD1
      - OBSERVIUM_BASE_URL=http://thor.box:8080
      - TZ=America/New_York
    volumes:
      - /etc/observium/logs:/opt/observium/logs
      - /etc/observium/rrd:/opt/observium/rrd
    networks:
      - back-tier
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - db

networks:
  back-tier:
      driver: bridge
```
(i removed the version specifiers during troubleshooting, wondering if a more up-to-date container existed that fixed the issue)

and here are the errors I'm getting:
on app:
```
[42] Verifying coonection to observium database.

mysql: [Warning] Using a password on the command line interface can be insecure.

ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0

```

and on db:

`2022-01-21 11:02:04 42 [Warning] Aborted connection 42 to db: 'unconnected' user: 'unauthenticated' host: '172.21.0.3' (This connection closed normally without authentication)`

Thanks in advance for any ideas
